export const CHANGE_VAT = 'CHANGE_VAT'
export const CHANGE_DISCOUNT = 'CHANGE_DISCOUNT'

export const UPLOAD_LOGO = 'UPLOAD_LOGO'
export const TOTAL_AMOUNT = 'TOTAL_AMOUNT'
export const AMOUNT_WITHOUT_TAXES = 'AMOUNT_WITHOUT_TAXES'